name: Main

on: [push]

jobs:
  build:
    name: Build frontend
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: actions-rs/toolchain@v1.0.0
        with:
          toolchain: stable
      - name: build
        env:
          NODE_ENV: production
        run: |
          npm install --dev
          npm run build

      - name: publish
        uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: rexagon/bytie-moe
          tag: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
