name: Main

on: [push]

jobs:
  build:
    name: Build frontend
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: actions-rs/toolchain@v1.0.0
        with:
          toolchain: stable
      - name: build
        env:
          NODE_ENV: production
        run: |
          npm install --dev
          npm run build

      - name: publish
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
          source: "dist"
          target: ${{ secrets.TARGET_FRONTEND }}
